apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: grafana-require-pomerium-jwt
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana # This matches the label applied to our test service
  jwtRules:
  - issuer: "authenticate.pomerium.kubezta.ga" # Adjust to match your Authenticate service URL
    forwardOriginalToken: true
    audiences:
      - grafana.pomerium.kubezta.ga # This should match the value of spec.host in the services Ingress
    fromHeaders:
      - name: "X-Pomerium-Jwt-Assertion"
    jwksUri: https://authenticate.pomerium.kubezta.ga/.well-known/pomerium/jwks.json # Adjust to match your Authenticate service URL.
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: grafana-require-pomerium-jwt
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana # This matches the label applied to our test service
  action: ALLOW
  rules:
  - when:
    - key: request.auth.claims[aud]
      values: ["grafana.pomerium.kubezta.ga"]
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: grafana
  namespace: default
spec:
  selector: app.kubernetes.io/name == 'grafana'
  ingress:
    - action: Allow
      source:
        namespaceSelector: projectcalico.org/name == 'pomerium'
        serviceAccounts:
          names: ["pomerium-proxy"] # Allow Pomerium proxy access only
  egress:
    - action: Allow
