apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
  - port: 2379
    name: http
  selector:
    app: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  labels:
    app: yaobank
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        version: v1
      annotations:
        inject.istio.io/templates: "sidecar,spire"
    spec:
      serviceAccountName: database
      containers:
      - name: database
        image: calico/yaobank-database:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2379
        command: ["etcd"]
        args:
          - "-advertise-client-urls"
          - "http://database:2379"
          - "-listen-client-urls"
          - "http://0.0.0.0:2379"
---
apiVersion: v1
kind: Service
metadata:
  name: summary
  labels:
    app: summary
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8000
  selector:
    app: summary
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: summary
  labels:
    app: yaobank
    database: reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary
  template:
    metadata:
      labels:
        app: summary
        version: v1
      annotations:
        inject.istio.io/templates: "sidecar,spire"
    spec:
      serviceAccountName: summary
      containers:
      - name: summary
        image: calico/yaobank-summary:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8000
  selector:
    app: customer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer
  labels:
    app: yaobank
    summary: reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
        version: v1
      annotations:
        inject.istio.io/templates: "sidecar,spire"
    spec:
      serviceAccountName: customer
      containers:
      - name: customer
        image: calico/yaobank-customer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yaobank
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.pomerium.io/policy: '[{"allow":{"and":[{"domain":{"is":"kubezta.ga"}}]}}]'
    ingress.pomerium.io/pass_identity_headers: "true"
spec:
  ingressClassName: pomerium
  rules:
  - host: customer.yaobank.pomerium.kubezta.ga
    http:
      paths:
      - backend:
          service:
            name: customer
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - customer.yaobank.pomerium.kubezta.ga
    secretName: customer.yaobank.pomerium.kubezta.ga-tls
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: customer
  namespace: default
spec:
  selector:
    matchLabels:
      app: customer
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/pomerium/sa/pomerium-proxy"]
    - source:
        namespaces: ["pomerium"]
  - to:
    - operation:
        methods: ["GET"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: summary
  namespace: default
spec:
  selector:
    matchLabels:
      app: summary
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/customer"]
    - source:
        namespaces: ["default"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: database
  namespace: default
spec:
  selector:
    matchLabels:
      app: database
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/summary"]
    - source:
        namespaces: ["default"]
---
